name = "Zemetro"
author = "Varg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa4c3ed735b0568b1af0fac021d51dbad327fc44685f9d8099c6a3fb041a9c51"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
