name = "Zemetro"
author = "Varg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e459b4345a7da12c9f495a0c18484353e8e37e1651defe51ad5d755fd2ca4b81"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
