name = "Zemetro"
author = "Varg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8b7459dacb7d4a99f8f257c43955b3a7b84c78406517e6dffeb1f96cac9b2ea"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
