name = "Zemetro"
author = "Varg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1425f6471023849f1d2508dba11795f4f39eb28e93d336f80f65ed5d07350c7c"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
